import { API } from '../core/api'
import { ApiOptions, NotificationList } from '../models'

/**
 * Notifications is an API module for managing notifications
 *
 * Notifications are generated by thread and account activity.
 *
 * @param {ApiOptions} opts API options object
 * @extends API
 */
export default class Notifications extends API {
  opts: ApiOptions
  constructor(opts: ApiOptions) {
    super(opts)
    this.opts = opts
  }

  /**
   * Retrieves all notifications generated by thread and account activity
   * @returns An array of Notification objects
   */
  async list() {
    const response = await this.sendGet('/api/v0/notifications')
    return response.data as NotificationList
  }

  /**
   * Marks a notifiction as read by ID
   *
   * @param id ID of the target notification
   * @returns Whether the operation was successful
   */
  async read(id: string) {
    const response = await this.sendPost(`/api/v0/notifications/${id}/read`)
    return response.status === 200
  }

  /**
   * Marks all notifictions as read
   * @returns Whether the operation was successful
   */
  async readAll() {
    return this.read('all')
  }
}
