/* GENERATED FROM message.proto. DO NOT EDIT MANUALLY. */
/* tslint:disabled */
/* eslint-disable */

export interface Message {
  type: Message.Type
  payload: any
  requestId: number
  isResponse: boolean
}

export namespace Message {
  export enum Type {
    PING = 'PING',
    PONG = 'PONG',
    THREAD_ENVELOPE = 'THREAD_ENVELOPE',
    CAFE_CHALLENGE = 'CAFE_CHALLENGE',
    CAFE_NONCE = 'CAFE_NONCE',
    CAFE_REGISTRATION = 'CAFE_REGISTRATION',
    CAFE_DEREGISTRATION = 'CAFE_DEREGISTRATION',
    CAFE_DEREGISTRATION_ACK = 'CAFE_DEREGISTRATION_ACK',
    CAFE_SESSION = 'CAFE_SESSION',
    CAFE_REFRESH_SESSION = 'CAFE_REFRESH_SESSION',
    CAFE_STORE = 'CAFE_STORE',
    CAFE_STORE_ACK = 'CAFE_STORE_ACK',
    CAFE_UNSTORE = 'CAFE_UNSTORE',
    CAFE_UNSTORE_ACK = 'CAFE_UNSTORE_ACK',
    CAFE_OBJECT = 'CAFE_OBJECT',
    CAFE_OBJECT_LIST = 'CAFE_OBJECT_LIST',
    CAFE_STORE_THREAD = 'CAFE_STORE_THREAD',
    CAFE_STORE_THREAD_ACK = 'CAFE_STORE_THREAD_ACK',
    CAFE_UNSTORE_THREAD = 'CAFE_UNSTORE_THREAD',
    CAFE_UNSTORE_THREAD_ACK = 'CAFE_UNSTORE_THREAD_ACK',
    CAFE_DELIVER_MESSAGE = 'CAFE_DELIVER_MESSAGE',
    CAFE_CHECK_MESSAGES = 'CAFE_CHECK_MESSAGES',
    CAFE_MESSAGES = 'CAFE_MESSAGES',
    CAFE_DELETE_MESSAGES = 'CAFE_DELETE_MESSAGES',
    CAFE_DELETE_MESSAGES_ACK = 'CAFE_DELETE_MESSAGES_ACK',
    CAFE_YOU_HAVE_MAIL = 'CAFE_YOU_HAVE_MAIL',
    CAFE_PUBLISH_PEER = 'CAFE_PUBLISH_PEER',
    CAFE_PUBLISH_PEER_ACK = 'CAFE_PUBLISH_PEER_ACK',
    CAFE_QUERY = 'CAFE_QUERY',
    CAFE_QUERY_RES = 'CAFE_QUERY_RES',
    CAFE_PUBSUB_QUERY = 'CAFE_PUBSUB_QUERY',
    CAFE_PUBSUB_QUERY_RES = 'CAFE_PUBSUB_QUERY_RES',
    ERROR = 'ERROR',
    CAFE_CONTACT_QUERY = 'CAFE_CONTACT_QUERY',
    CAFE_CONTACT_QUERY_RES = 'CAFE_CONTACT_QUERY_RES',
    CAFE_PUBSUB_CONTACT_QUERY = 'CAFE_PUBSUB_CONTACT_QUERY',
    CAFE_PUBSUB_CONTACT_QUERY_RES = 'CAFE_PUBSUB_CONTACT_QUERY_RES'
  }
}

export interface Envelope {
  message: Message
  sig: string
}

export interface Error {
  code: number
  message: string
}
